### ISSUE TITLE
Integration is not accessible in HA

### ISSUE THREAD

**Issue by sopach** [mathieu-mp/homeassistant-intex-spa#106]
I try add integration to Home Assistant but integration is not visible in integration list. As you can see on screenshot. Version Home Assistant is 2023.5.4 and Frontend 20230503.3 - latest. HA is running on Synology DS220+ in docker. Where can be problem please ? Thank you.

![image](https://github.com/mathieu-mp/homeassistant-intex-spa/assets/21358361/b257bf49-4629-4d6b-9375-4b09e614d511)

**Comment by mathieu-mp** [comment]
Please use HACS as advised on the README
