### ISSUE TITLE
can't configure

### ISSUE THREAD

**Issue by KennethSmit** [mathieu-mp/homeassistant-intex-spa#38]
I did the installation via HACS (with a detour). Continued configuration does not work. If I go through the steps as described, after clicking the +, I do not encounter the intex application. How can I add it? At the entities you will encounter in the intex spa update

Homeassistant 2022.8.7
Rasperry Pi4

**Comment by mathieu-mp** [comment]
Hi @KennethSmit,

Well, you did have to add the repository to the repositories list known by HACS, did you ?
Any other detour ?

Did you restart Home Assistant ? Any integration added via HACS need a restart to be displayed in the integration list of Home Assistant.

**Comment by KennethSmit** [comment]
Hi,
I took a different route for the HACS. Not included by default. Did it through your GITHUB file. He is now also between the HACS (see photo
<img width="1169" alt="Schermafbeelding 2022-08-26 om 14 16 37" src="https://user-images.githubusercontent.com/63705333/186901947-e3f603ea-5a4a-4a34-9383-c996100f58b3.png">
)

after that i resarted de HA (several times :-))

**Comment by KennethSmit** [comment]
<img width="477" alt="Schermafbeelding 2022-08-26 om 14 15 20" src="https://user-images.githubusercontent.com/63705333/186902118-b1d4a292-a5df-4668-b283-6b3cfe2ba2a9.png">
i can't find it between the intergrations

**Comment by mathieu-mp** [comment]
Quite fun... Intex Spa was added 31 minutes ago to HACS defaults ! 
I suggest you to remove intex spa as you added it manually, then re-add it from HACS default repository

Let me know how it goes...

**Comment by mathieu-mp** [comment]
Just did it myself and it seems to be all good !

**Comment by KennethSmit** [comment]
I removed the HACS, reset the HA and installed the Intex (it was now in the default). Installation went well as you can see. After HACS installation I reset the HA
<img width="1184" alt="Schermafbeelding 2022-08-26 om 14 36 25" src="https://user-images.githubusercontent.com/63705333/186905062-b58b93b7-749e-4c10-aa43-54a1bd8843e1.png">

**Comment by KennethSmit** [comment]
<img width="479" alt="Schermafbeelding 2022-08-26 om 14 36 59" src="https://user-images.githubusercontent.com/63705333/186905315-992c5043-9ddc-4acc-8938-218b592c24dc.png">

And still it in the intergrations

**Comment by mathieu-mp** [comment]
Spa is not happy 😭 

Please:
1. Remove the intex_spa integration from HACS
2. Remove config/custom_components/intex_spa folder, and any folder you created by making your "detour" 🚲 
3. Developer Tools > Restart
4. Add  the intex_spa integration from HACS
5. Developer Tools > Restart
6. Settings > Device and Services > + Add Integration > Intex Spa
7. Set the parameters
8. Come and tell us that you (hopefully) won !

**Comment by KennethSmit** [comment]
done step by step (again). Result remains that I cannot add the INTEX via configuration (step 6 does not work)

**Comment by mathieu-mp** [comment]
Sorry, but I have no idea about the eventual cause of this behavior...
...it doesn't look specific to this integration, so maybe you can find help on similar behaviors for other integrations ?

Anyway, think again on what you exactly did as a "detour" to install the integration, the solution might be there !

Please tell us about this issue :muscle:

**Comment by KennethSmit** [comment]
i made a backup before I started with the Intex integration. I just restored the backup and then went through your steps. Stick to step 6 again

**Comment by mathieu-mp** [comment]
😨 What happens with a random other integration installed from HACS default ?

**Comment by KennethSmit** [comment]
hello, after the HACS update to 1.27.1 and the reset the INTEX integration came up automatically. Now I can install and everything works.
