### ISSUE TITLE
Programming the time for water filtering and sanitizer

### ISSUE THREAD

**Issue by nestor1832** [mathieu-mp/homeassistant-intex-spa#41]
Hello and thank you for the work, it is really useful to manage the SPA with Home assistant.

I use HS to program the duration of the filtration and the duration for the sanitizer. I noticed that I can't choose the duration of work as on the Intex app.

When I start the filtration or sanitizer, it defaults to the time that was selected on the SPA control pad.

Would it be possible to send the duration for the desired filtration and sanitizer to the SPA from HS ?
1, 2, 3, 4, 5, 6, 7, 8 hours

Thank you very much !

**Comment by mathieu-mp** [comment]
Hi @nestor1832 

Sorry I missed to answer to your feature request. And thank you for your kind comment.

It might technically be possible to set the duration while triggering the command, but here is no official documentation stating how to achieve this. 
This integration is based on a time-consuming community work to identify main commands and settings. And much decompiled Intex code reading.
It might not look like it, but each command have been a small achievement in itself !
I tried to understand how this durations feature works by analysing exchanges between the app, the cloud and the spa, but I couldn't make it.

I would suggest that you use Home Assistant automations or Node Red to deal with filtering or sanitizer durations. It is how I personally answer to this need.
I hope this workaround will address your need.
I do not plan to add this feature.

Thank you again for your time and issue.

Mathieu.
