### ISSUE TITLE
Please elaborate on why current temperature is disabled by default

### ISSUE THREAD

**Issue by verwilst** [mathieu-mp/homeassistant-intex-spa#50]
Currently the readme says the current temp. sensor is disabled by default. Would it be possible to update that part of the documentation why exactly that is, and maybe what the 'risks' are when enabling it?

**Comment by mathieu-mp** [comment]
Hi @verwilst,

Thank you for your interest and relevant question.

The current temperature info is already available as an attribute of the climate entity, and can be exposed as a status via a template.
There is no risk or side effect to enable the current temperature sensor feature. It was added following #36, to ease monitoring or graphing.
It has not been enabled by default as it duplicates already existing data in the home assistant database, while most of the users won't need it.

I will update the docs with this mention.

Regards, Mathieu.

**Comment by mathieu-mp** [comment]
Implemented by #60
