### ISSUE TITLE
[Documentation] Pairing without the Intex App

### ISSUE THREAD

**Issue by FreezyExp** [mathieu-mp/homeassistant-intex-spa#51]
Hi, not sure if this is a good place to post this, but I wanted to share my findings somewhere.

We bought a intex spa with wifi (SB-HSWF20), but sadly their app is terrible and cloud based. 
I just wanted the spa in Home Assistant. 
After a bit of poking and prodding, I managed to get it connected without the intex app.

Steps: TLDR; 
1. The Intex Spa uses ESPTouch (from Espressif), pair it using some open source app using broadcast option (not multicast)
2. When the spa is paired, it requires something to listen to it's ports or it seems to disconnect

How I got it to pair without the intex cloud and app:
1. Using: https://github.com/EspressifApp/EsptouchForAndroid
- I ran the EspTouch to pair the spa
- After it connected, the wifi light did not stay lit :-(
- Either my wifi connection was poor, or some kind of handshake was needed
- The spa device disconnected from the wifi :-(

Notes on EspTouch:
- Requires local network data in order to broadcast the details to the spa
- (I'm not sure how this protocol operates, but this is what I concluded) as having wifi data disabled prevented the app from working.
- I blocked all internet for my phone on my router, just to be sure no info could leak

2. In Home Assistant - HACS : find and install the Intex intergration

- In HA prepare all the data to add the new intex spa device (but wait with connecting)
- Press and hold the C/F Wifi button on the spa unit, the wifi will start blinking for a minute
- Use the EspTouch app to connect the unit again
- As soon as it connects, connect the HA intex device setup, the wifi light will remain lit

I figure this out today by taking a peek in inside of the Management APK to check what they were doing and what the protocol was being used.
I found the espressif ESPTouch code, my spa is using V1 not V2. 

Perfect, their app is worthless anyways and now my spa is not connected to the internet, only to my local HA network.
Thanks for this

**Comment by mathieu-mp** [comment]
Very interesting, thanks @FreezyExp !

I may add it the docs, and add a page to `mathieu-mp/intex-spa` python package. It could help people !

**Comment by FreezyExp** [comment]
perhaps you could even find a python implementation for the ESPTouch code

Seems like others have already done that work, but... as it is a onetime setup that requires a wireless interface, perhaps declaring it as a setup step to hint on how to pair it would work just as well without adding third party dependencies.

https://github.com/KurdyMalloy/EsptouchPython
https://github.com/CaptainDouche/esp_smartcfg_linux

**Comment by mathieu-mp** [comment]
This seems far outside the scope of this integration. More, the python package is an alpha version.
I will suggest this path to the user in the documentation, but I won't add this feature.

**Comment by jojeju9428** [comment]
hello, 
I also have an SB-HSWF20, I managed to configure it directly and integrate it into HA thanks to your documentation
Could you tell me if you can manage it with automation?
When I try to automate, the SPA shuts off after 2 hours
Thanks

**Comment by mathieu-mp** [comment]
> Could you tell me if you can manage it with automation?
Yes !
> When I try to automate, the SPA shuts off after 2 hours
The duration is set on the panel control side, not on the integration side. Use the spa panel control to change the duration of the feature you want to automate. Look for the HST/HDT settings in the user manual.
After that, the HDT will be reused when the feature is triggered from the integration.

**Comment by Nielm75** [comment]
I would like to share an observation that might help other users experiencing unexpected Wi-Fi disconnections.
I discovered that on my 2021 PureSpa (SC-WF20 Wi-Fi module), the control panel lock does not disable the Wi-Fi pairing function. Even when the panel is locked and all other buttons are disabled, holding the °C/°F button for about 5 seconds still puts the Wi-Fi module into pairing mode.
As soon as pairing mode is activated, the spa disconnects from the home Wi-Fi network and becomes unavailable in both the Intex app and Home Assistant until it is paired again.
Another user confirmed the same behavior on a newer Tuya-based PureSpa, so this does not appear to be limited to the older SC-WF20 hardware.
I suspect this could explain at least some of the "random" Wi-Fi disconnections reported by users. An unintended long press (or possibly conductive moisture/salt residue on the touch panel) could trigger pairing mode without the user realizing it.
This is not an issue with this Home Assistant integration, but rather something to be aware of when troubleshooting Wi-Fi connectivity problems with Intex spas.

**Comment by Freev4lley** [comment]
Hello, 

in case anyone is interested, I got it workink without the Intrex App! I downloaded the app FY WiFi Setup from the Play Store and connected my Intex Spa with my Network without any Trouble. Then the Integration in Home Assistant works like a charm!

Best Regard Tino
