### ISSUE TITLE
The heating (flame) is flashing green instead of red if I turn on heating

### ISSUE THREAD

**Issue by nobirdnobird** [mathieu-mp/homeassistant-intex-spa#57]
1st of all thank you for implementing this module in HA ! 

I have a "Intex Pure SPA Bubble GreyWood XXL Deluxe 28442" an I have the issue that if I turn on heating via HA the heating symbol (flame) is switching to flashing green and it seems a timer is activated, because there is shown a three hour timer and the flame symbol in the controller device.

If I press the flame button manually there is a red flame shown and the heating is starting.

**Comment by mathieu-mp** [comment]
Hi @nobirdnobird ,

When the heating is enabled via the integration, it uses the timer settings defined on the physical remote control.
Removing the Heater Duration Timer from the remote control should make the home assistant integration set the spa expected temperature without timer.

To remove the Heater Duration Timer, see the [Operation Manual (Wifi wireless Spa Manual)](https://intexcorp.com/replacement-parts/spas/purespa-greywood-deluxe/85in-x-28in/2023/28441e/#replacement-parts-content), section "Spa Control Panel".

Let us know if the solves your issue.

**Comment by mathieu-mp** [comment]
Hi @nobirdnobird ,
Any news on this ?

**Comment by nobirdnobird** [comment]
Hi @mathieu-mp,
sorry for the delay answering.

I found out, that the green flame stand for desired temperature reached and it is "on" but not heating anymore.

So every thing is fine.

BR

**Comment by nobirdnobird** [comment]
Just to add a request for a feature:
If the desired temperature is reached, the heating symbol should change from red to green as it is shown on the control unit.
BR

**Comment by mathieu-mp** [comment]
Hi @nobirdnobird 

Thank you for your response.
Your feature request is legitimate, but can't be done in the current state of our knowledge about the status message returned by the spa (cf. #46)
