### ISSUE TITLE
Intégration Error

### ISSUE THREAD

**Issue by Chezoimsvc** [mathieu-mp/homeassistant-intex-spa#65]
Hello and thank you for this development

I have an error during the integration of the device and I cannot configure this one.

**When I follow these steps :**

_1 - Go to your Home Assistant instance
2 - Go to "Settings" -> "Devices & Services" -> Click "+"
3 - Search for "Intex Spa" -> Select it_

**I have the following error message :**

Error
The configuration stream could not be loaded : {"message":"Invalid handler specified"}

What can I do to solve this pb ?

Thanks in advance

**Comment by mathieu-mp** [comment]
Hi @Chezoimsvc 
Please mention your home assistant version and provide logs

**Comment by Chezoimsvc** [comment]
Hello Mathieu,

My version is : 
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Interface utilisateur : 20230705.1 - latest

And I have the following error in the log :

Logger: homeassistant.config_entries
Source: config_entries.py:874
First occurred: 17:08:18 (2 occurrences)
Last logged: 17:08:26

Error occurred loading flow for integration intex_spa: cannot import name 'IntexSpa' from 'intex_spa' (/usr/local/lib/python3.11/site-packages/intex_spa/__init__.py)

**Comment by mathieu-mp** [comment]
Hi @Chezoimsvc
I assume you've already tried reinstalling the integration from HACS.
So I'll check the behavior of initializing an intex_spa instance with the software versions you mentioned, as it could be a lead.

**Comment by Chezoimsvc** [comment]
Hi @mathieu-mp 

Yes, I redid the whole installation from HACS. (deleting and reinstalling with all the restarts between the different steps)

I also redid the installation of the intex-spa 0.8.4 package but I still have the same problem.

**Comment by Chezoimsvc** [comment]
HI @mathieu-mp 


I just updated Home Assistant:

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Interface utilisateur : 20230705.1 - latest

Good news, the problem has disappeared !

Thank you for your help and for great dev

**Comment by mathieu-mp** [comment]
Great, that's good news!
And thank you for your follow-up
