### ISSUE TITLE
Does not work after update to 2023.08

### ISSUE THREAD

**Issue by djg-io** [mathieu-mp/homeassistant-intex-spa#66]
Dees anyone work in this version (after update to 2023.08)? Before update was fine.
My SPA is PureSpa Greywood Deluxe v22111, firmware 1.0.300. Intex aplication is working, spa is online.
Edit
My mistake, it was a filter error causing the disconnect (E90). I'm sorry:/

**Comment by mathieu-mp** [comment]
Thank you for updating, enjoy your spa !
