### ISSUE TITLE
Docker: Server error and messes up HA installation

### ISSUE THREAD

**Issue by MichNLGithub** [mathieu-mp/homeassistant-intex-spa#69]
When install the HACS package and find the Integration by name an error pop up: Config-flow could not load: 500 Internal Server Error Server got itself in trouble

**Comment by MichNLGithub** [comment]
There is indeed a big bug in your HACS script, when i download it in HACS and restart, HA doesn't start anymore.
Did a clean setup an tried again and downloaded the files from HACS and restart it and HA doesn't restart again anymore.

It messes up HA so must to a 3th time reinstall of HA...

**Comment by Elkropac** [comment]
Hello,
i just googled your error message and there could be some problem with your external url setting in HA, can you please check this discussion?

https://community.home-assistant.io/t/official-smartthings-integration-error-config-flow-could-not-be-loaded-500-internal-server-error-server-got-itself-in-trouble/393292/8

**Comment by MichNLGithub** [comment]
@Elkropac thanks for your answer, i had a docker installation running of HA, i switched to HA OS and it worked!!
Maybe an internal docker system fault?
