### ISSUE TITLE
Integration works flawlessly for Intex Pure Spa 2021 - SC-WF20

### ISSUE THREAD

**Issue by olivierbardot** [mathieu-mp/homeassistant-intex-spa#91]
Hello

Thanks a lot for this nice HA integration which works perfectly

For information purposes, here is my configuration :

Home Assistant OS on RaspPi4
    Core 2024.3.3
    Supervisor 2024.03.1
    Operating System 12.1
    Interface utilisateur 20240307.0

Intex Spa
Intex Pure Spa 2021 - SC-WF20
Version : 21SC-WF20**A0

Have a nice day !
Cheers
Olivier

**Comment by mathieu-mp** [comment]
Thank you for your feedback, it's much appreciated !
Enjoy your Spa for the coming season !
